builders:
  build_license_collector:
    import: 'package:build_license_collector/builder.dart'
    builder_factories: [createBuilder]
    build_extensions:
      "$package$":
        - lib/src/licenses.json
    required_inputs:
      - .module.library
    defaults:
      options:
        output: "lib/src/licenses.g.dart"
        entrypoints: web/*.dart
        dart:
          - _internal
          - _js_annotations
          - async
          - collection
          - convert
          - core
          - developer
          - js_interop
          - js_interop_unsafe
          - math
          - typed_data
    auto_apply: dependents
    build_to: source
