builders:
  build_license_collector:
    import: 'package:build_license_collector/builder.dart'
    builder_factories: [createBuilder]
    build_extensions:
      "$package$":
        - lib/src/licenses.json
    required_inputs:
      - .module.library
    defaults:
      options:
        output: "lib/src/licenses.g.dart"
        entrypoints: web/*.dart
    auto_apply: dependents
    build_to: source
